"""add discography_link

Revision ID: d8416b13438e
Revises: fe99126f2607
Create Date: 2026-02-14 15:17:05.848336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8416b13438e'
down_revision: Union[str, Sequence[str], None] = 'fe99126f2607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discographies', sa.Column('discography_link', sa.String(), nullable=True))
    # op.alter_column('users', 'login_id',
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.String(length=12),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'login_id',
    #            existing_type=sa.String(length=12),
    #            type_=sa.VARCHAR(length=10),
    #            existing_nullable=False)
    op.drop_column('discographies', 'discography_link')
    # ### end Alembic commands ###
