"""init

Revision ID: fe99126f2607
Revises: 
Create Date: 2026-02-12 14:38:20.134149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe99126f2607'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discographies',
    sa.Column('discography_id', sa.Integer(), nullable=False),
    sa.Column('discography_title', sa.String(), nullable=False),
    sa.Column('discography_num', sa.Integer(), nullable=True),
    sa.Column('discography_type', sa.String(), nullable=False),
    sa.Column('released_date', sa.Date(), nullable=False),
    sa.Column('playtime_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('discography_id')
    )
    op.create_index(op.f('ix_discographies_discography_title'), 'discographies', ['discography_title'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=12), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('listen_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discography_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('listened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discography_id'], ['discographies.discography_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listen_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_discographies_discography_title'), table_name='discographies')
    op.drop_table('discographies')
    # ### end Alembic commands ###
